default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url-shortener_development

test:
  <<: *default
  database: url-shortener_test

production:
  <<: *default
  database: url_shortener_production
  username: url_shortener
  password: <%= ENV['FBCLONE_DATABASE_PASSWORD'] %>